### ISSUE TITLE
Error not properly handled. Powershell will exit - [process exited with code 3762504530 (0xe0434352)]

### ISSUE THREAD

**Issue by KDAM71** [microsoft/winget-command-not-found#7]
I don't know if I am making a mistake but when I run " Import-Module -Name Microsoft.WinGet.CommandNotFound" in Powershell 7.4.2 on windows home 11 23h2, Powershell gives the following error:

"An error has occurred that was not properly handled. Additional information is shown below. The PowerShell process will exit.
Unhandled exception. System.Management.Automation.CmdletInvocationException: An error occurred while connecting to the catalog.
 ---> Microsoft.WinGet.Client.Engine.Exceptions.CatalogConnectException: An error occurred while connecting to the catalog.
   at Microsoft.WinGet.Client.Engine.Commands.Common.FinderCommand.GetPackageCatalog(CompositeSearchBehavior behavior)
   at Microsoft.WinGet.Client.Engine.Commands.Common.FinderCommand.FindPackages(CompositeSearchBehavior behavior, UInt32 limit, PackageFieldMatchOption match)
   at Microsoft.WinGet.Client.Engine.Commands.Common.FinderExtendedCommand.FindPackages(CompositeSearchBehavior behavior, PackageFieldMatchOption match)
   at Microsoft.WinGet.Client.Engine.Commands.FinderPackageCommand.<>c__DisplayClass1_0.<Find>b__0()
   at Microsoft.WinGet.Client.Engine.Commands.Common.ManagementDeploymentCommand.Execute[TResult](Func`1 func)
   at Microsoft.WinGet.Client.Engine.Commands.FinderPackageCommand.Find(String psPackageFieldMatchOption)
   at Microsoft.WinGet.Client.Commands.FindPackageCmdlet.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
   --- End of inner exception stack trace ---
   at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
   at System.Management.Automation.PowerShell.EndInvoke(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at Microsoft.WinGet.CommandNotFound.WinGetCommandNotFoundFeedbackPredictor.WarmUp()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

[process exited with code 3762504530 (0xe0434352)]
You can now close this terminal with Ctrl+D, or press Enter to restart."

If it's not my mistake I thought you might want to know.

Kind regards, Klaas

**Comment by xky0007** [comment]
Any update to fix this?

**Comment by JamesDBartlett3** [comment]
Same issue here.

**Comment by mehrshaad** [comment]
Same Issue here on windows 11

**Comment by luoling8192** [comment]
I can NOT use pwsh caused by this issue, after I have installed PowerToys pwsh plugin

**Comment by carlos-zamora** [comment]
Looking to fix this as a part of https://github.com/microsoft/winget-command-not-found/pull/10. After that merges, I'll push out a new release.

In the meantime, if you installed the plugin via PowerToys, you can uninstall it in the PowerToys settings page > Command Not Found
![PowerToys Settings_ytF86bd4jk](https://github.com/microsoft/winget-command-not-found/assets/11050425/299a0896-95ba-4ad1-b1f1-a608e002642d)

That'll make the CommandNotFound module not load during startup and let you get back to using pwsh 😊

**Comment by carlos-zamora** [comment]
FYI, here's the new release: https://github.com/microsoft/winget-command-not-found/releases/tag/v1.0.3

Enjoy! 😊

**Comment by ZStoner** [comment]
As a temporary workaround:
For those that may not have the updated version of Microsoft.WinGet.CommandNotFound, this particular workaround appeared to work for me, and I still have v1.0.2 of "CommandNotFound".

If you have this in your PWSH `$PROFILE` script...
> `Import-Module Microsoft.WinGet.CommandNotFound`

...Change it to use the `Get-Module | Import-Module` syntax...
```powershell
Get-Module Microsoft.WinGet.CommandNotFound | Import-Module
```

I was then able to do this from the standard CMD shell _(not a PS prompt)_:
```bat
C:\Temp> pwsh -c "'{0:yyMMdd.HHmm}' -f [datetime]::UtcNow"
241002.2356
```

----------
**Option # 2**: _Add the_ `-NoProfile`/`-nop` _flag to pwsh..._
This prevents loading your `$PROFILE` script with your CMD-executed command...
```bat
C:\Temp> pwsh -nop -c "'{0:yyMMdd.HHmm}' -f [datetime]::UtcNow"
241003.0013
```

Disclaimers:
* I give no guarantees this will work on all systems.
* I can only claim that after making the profile change and saving it, my DOS prompt was immediately able to execute it without the "CommandNotFound" errors.  :smile:

**Comment by Petalzu** [comment]
Incidentally, if you don't have the Command Not Found option set in powertoys but still have that error, it may have been set previously but not completely removed due to some issue.

According to https://github.com/microsoft/winget-cli/discussions/844, go to windows settings>apps>app execution aliases>toggle off winget.exe there and you will find the source of the problem.

![Image](https://github.com/user-attachments/assets/5a510db6-4b5b-4566-bb07-b957325c2ba7)

C ： \Users\ ••••••\Documents\PowerShelI\Microsoft.PowerSheII_profiIe.ps1

Follow the instructions to find the file and remove the line similar to the following to fix it.

`Import-Module -Name Microsoft.WinGet.CommandNotFound`

**Comment by exSnake** [comment]
When you run powershell as administrator with Command Not Found installed this error occurs again

**Comment by RMG112096** [comment]
I still have this issue. When I lose internet connection and just open powershell with or without running a command I get the same issue as OP. Have to use the integrated powershell to avoid issues. 

![Image](https://github.com/user-attachments/assets/0c3015e4-d7bd-4606-a437-48638fb7f459)

**Comment by CeSiumUA** [comment]
I still have this issue with version v0.90.1. Completely the same, as @RMG112096 has mentioned above

**Comment by lancechant** [comment]
Just for anyone in the future having this issue, ensure the module has actually been updated, as mine was still on `1.0.2` you can check by running `Get-InstalledModule -Name Microsoft.WinGet.CommandNotFound` and updating with `Update-Module -Name Microsoft.WinGet.CommandNotFound`
